//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 resource.rc 使用
//
#define ID_ICON                         1
#define IDD_MAIN                        101
#define IDR_MENU1                       103
#define IDR_MENU2                       113
#define IDD_SEARCH                      131
#define IDD_SET                         133
#define IDD_LRC                         135
#define IDD_MINI                        136
#define IDD_MINILRC                     137
#define IDC_OK                          1000
#define IDC_PLAY                        1000
#define IDC_btnPLAY                     1000
#define IDC_MList                       1004
#define IDC_STOP                        1005
#define IDC_btnSTOP                     1005
#define IDC_PAUSE                       1006
#define IDC_btnPAUSE                    1006
#define IDC_LAST                        1007
#define IDC_btnLAST                     1007
#define IDC_NEXT                        1008
#define IDC_btnNEXT                     1008
#define IDC_EDITNOW                     1009
#define IDC_COMBOSX                     1010
#define IDC_MUSIC_SLIDER                1011
#define IDC_SOUND_SLIDER                1012
#define IDC_BTN_ADD                     1013
#define IDC_btnADD                      1013
#define IDC_btnMINI                     1014
#define IDC_BTN_DEL                     1015
#define IDC_btnDEL                      1015
#define IDC_SOF                         1016
#define IDC_btnMINILRC                  1017
#define IDC_EDITTIME                    1021
#define IDC_CLEAN                       1022
#define IDC_btnCLEAN                    1022
#define IDC_EDITLIST                    1023
#define IDC_EDITVOICE                   1024
#define IDC_HID                         1025
#define IDC_btnHIDE                     1025
#define IDC_EDITSTIME                   1030
#define IDC_btnSLIST                    1031
#define IDC_btnOLIST                    1032
#define IDC_CSL                         1033
#define IDC_COL                         1034
#define IDC_btnUP                       1035
#define IDC_btnDOWN                     1036
#define IDC_Title                       1037
#define IDC_Artist                      1038
#define IDC_Album                       1039
#define IDC_MUSICNAME                   1042
#define IDC_btnSEARCH                   1045
#define IDC_BAIDU                       1046
#define IDC_SOGOU                       1047
#define IDC_SOSO                        1048
#define IDC_btnSLEEP                    1049
#define IDC_LIST                        1049
#define IDC_CANCEL                      1050
#define IDC_btnLRC                      1050
#define IDC_SLEEPTIME                   1052
#define IDC_R                           1053
#define IDC_G                           1054
#define IDC_LRCList                     1055
#define IDC_B                           1055
#define IDC_REFRESH                     1056
#define IDC_FOLLOW                      1057
#define IDC__MUSIC_SLIDER               1063
#define IDC__btnLAST                    1064
#define IDC__btnPLAY                    1065
#define IDC__btnNEXT                    1066
#define IDC__btnPAUSE                   1067
#define IDC__btnSTOP                    1068
#define IDC__SOF                        1070
#define IDC__SOUND_SLIDER               1071
#define IDC__EDITNOW                    1072
#define IDC__COMBOSX                    1073
#define IDC_MINILRC                     1074
#define ID_MOpen                        40001
#define ID_menADD                       40001
#define ID_MABOUT                       40002
#define ID_menABOUT                     40002
#define ID_MPLAY                        40003
#define ID_menPLAY                      40003
#define ID_MPAUSE                       40004
#define ID_menPAUSE                     40004
#define ID_MSTOP                        40005
#define ID_menSTOP                      40005
#define ID_MLAST                        40006
#define ID_menLAST                      40006
#define ID_MSELF                        40008
#define ID_menSELFLOOP                  40008
#define ID_MLIST                        40009
#define ID_menLISTLOOP                  40009
#define ID_MRAND                        40010
#define ID_menRANDOM                    40010
#define ID_MDEL                         40011
#define ID_menDEL                       40011
#define ID_MEXIT                        40012
#define ID_menEXIT                      40012
#define ID_MNEXT                        40013
#define ID_menNEXT                      40013
#define ID_MCLEAN                       40014
#define ID_menCLEAN                     40014
#define ID_MHID                         40015
#define ID_menHIDE                      40015
#define ID_traPLAY                      40016
#define ID_traPAUSE                     40017
#define ID_traSTOP                      40018
#define ID_traLAST                      40019
#define ID_traNEXT                      40020
#define ID_traSELFLOOP                  40021
#define ID_traLISTLOOP                  40022
#define ID_traRANDOM                    40023
#define ID_traEXIT                      40024
#define ID_traRESUME                    40025
#define ID_traCANCEL                    40026
#define ID_menSLIST                     40027
#define ID_menOLIST                     40028
#define ID_menVUP                       40029
#define ID_menVDOWN                     40030
#define ID_traVUP                       40031
#define ID_traVDOWN                     40032
#define ID_menSOF                       40033
#define ID_traSOF                       40034
#define ID_menSET                       40035
#define ID_traSET                       40036
#define ID_traSEARCH                    40037
#define ID_menLRC                       40038
#define ID_traLRC                       40039

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         40040
#define _APS_NEXT_CONTROL_VALUE         1078
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
